AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for
  running Kittens Carousel Static Website on EC2.
  
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for secure connection.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: aws-laura
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      Tags:
        - Key: Name 
          Value: !Sub Web Server of ${AWS::StackName} 
      UserData: 
        Fn::Base64: 
          !Sub |
            #! /bin/bash
            yum update -y 
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/laura-hill/my-repository/main/aws/projects/Project-101-bear-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/bear1.jpg
            wget $FOLDER/bear2.jpg
            wget $FOLDER/bear3.jpg
            wget $FOLDER/bear4.jpg
            systemctl start httpd
            systemctl enable httpd

Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName