AWSTemplateFormatVersion: 2010-09-09
Description: |
    Cloudformation Template for wildies carousel static website deployed on s3. This static website is distributed by cloudfront. Cloudfront DNS is published by Route 53 using full domain name.
Parameters:
    DomainName:
      Description: DNS Name of existing Amazon Route 53 hosted zone ex. wildies.us
      Type: AWS::Route53::HostedZone::Id
    WildiesDomainName:
      Description: Full domain name for the App. ex. wildies.techtoyousoon.us
      Type: String
      AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  WildiesBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Ref WildiesDomainName
      WebsiteConfiguration: 
        IndexDocument: index.html
  WildiesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WildiesBucket
      PolicyDocument: 
        Statement:
          - Sid: PublicReadforStaticWebsite
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WildiesBucket', /*]]
            # !Sub "${WildiesBucket.Arn}/*"
  WildiesCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref WildiesDomainName #required
      DomainValidationOptions:
        - DomainName: !Ref WildiesDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS
  WildiesDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DomainName
      RecordSets: 
        - Name: !Ref WildiesDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt WildiesCloudfront.DomainName
  WildiesCloudfront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: #required
        Aliases: 
        - !Ref WildiesDomainName
        Comment: Cloudfront Distribution pointing to Wildies S3 bucket
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          Compress: true
          ForwardedValues: 
            Cookies: 
              Forward: none
            QueryString: true
          TargetOriginId: WildiesOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: 'http2'
        Origins: 
        - DomainName: !Select [2, !Split ["/", !GetAtt WildiesBucket.WebsiteURL]]
          Id: WildiesOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate: 
          AcmCertificateArn: !Ref WildiesCertificate
          SslSupportMethod: sni-only
Outputs:
  BucketName: 
    Description: S3 Bucket URL for Wildies Website
    Value: !GetAtt WildiesBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Wildies Cloudfront
    Value: !GetAtt WildiesCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref WildiesDomainName